/* Database schema to keep the structure of entire database. */

CREATE TABLE animals (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100),
    date_of_birth DATE,
    escape_attempts INTEGER,
    neutered BOOLEAN,
    weight_kg DECIMAL
);

-- Alter animals table to add species column
    ALTER TABLE animals
    ADD COLUMN species text;

-- Update species column to digimon for all animals that have a name ending in mon
    UPDATE animals
    SET species = 'digimon'
    WHERE name LIKE '%mon';

-- Update species to pokemon if not already assigned a species
    UPDATE animals
    SET species = 'pokemon'
    WHERE species IS NULL;
